### ISSUE TITLE
Error when attempting to load or create a new project

### ISSUE THREAD

**Issue by misssines** [amathislab/dlc2action_annotation#15]
I encountered an issue while trying to both load a project and create a new project. 

The script successfully creates a folder and symbolic links.

The following error occurs when attempting to load the project:

<img width="944" alt="Screenshot 2024-09-08 at 22 34 41" src="https://github.com/user-attachments/assets/c3aa8db6-9f94-437c-82f9-815f72a6aae6">

**Comment by andybonnetto** [comment]
Need to change the path management in the folder creation

**Comment by andybonnetto** [comment]
Fixed
